version: "3.7"
services:
    webserver:
        links:
            - mail
        environment:
            - DOMAIN=localhost
            - PRIVATE_KEY=
            - ENVIRONMENT=DEVELOPMENT
            - DB_HOST=db
            - DB_USERNAME=docker
            - DB_PASSWORD=docker
            - DB_DATABASE=dev
            - EMAIL_HOST=mail
            - EMAIL_PORT=1025
            - OPCACHE_VALIDATE_TIMESTAMPS=1
    mail:
        build: "docker/mail"
        ports:
            - "1025:1025"
            - "8025:8025"
    db:
        environment:
            - MYSQL_USER=docker
            - MYSQL_PASSWORD=docker
            - MYSQL_DATABASE=dev
