webserver:
    build: "docker/webserver/php72"
    links:
        - db
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./www:/var/www/html
        - ./docker/webserver/logs:/var/log
        - ./docker/webserver/letsencrypt:/etc/letsencrypt
db:
    build: "docker/db"
    ports:
        - "3306:3306"
    volumes:
        - ./docker/db/data:/var/lib/mysql/
    environment:
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        # Set credentials per environment
        # i.e. in docker-compose.override.yml
